### ISSUE TITLE
Error: Cannot find module '/Users/hokkinfong/code/mdx-vue-deck/node_modules/@babel/runtime/helpers/interopRequireWildcard'

### ISSUE THREAD

**Issue by luckydonald** [godkinmo/mdx-vue-deck#1]
```bash
$ yarn run mdx-vue-deck build ./test.mdx

internal/modules/cjs/loader.js:605
    throw err;
    ^

Error: Cannot find module '/Users/hokkinfong/code/mdx-vue-deck/node_modules/@babel/runtime/helpers/interopRequireWildcard'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/path/to/project/node_modules/mdx-vue-deck/lib/cli.js:4:31)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
error Command failed with exit code 1.
```

So this probably shouldn't be a symlink:
https://github.com/godkinmo/mdx-vue-deck/blob/9f80b930535113f20e5ea046cf4e25f6b3a00aeb/src/mdx/deck.mdx

**Comment by godkinmo** [comment]
Thank, fixed

**Comment by hmuir28** [comment]
I'm getting the same error... I'm wondering if it's something which is happening locally, since @godkinmo commented he fixed it.

![image](https://user-images.githubusercontent.com/20231944/72689037-bb693980-3ad2-11ea-967c-4b58f0247cd7.png)

**Comment by godkinmo** [comment]
Maybe you are using the old version, it is working fine

![Screenshot 2020-01-21 at 1 41 22 AM](https://user-images.githubusercontent.com/9634816/72747298-2dcf3c00-3bef-11ea-842d-b2c4fa21b54e.png)
![Screenshot 2020-01-21 at 1 41 19 AM](https://user-images.githubusercontent.com/9634816/72747306-30ca2c80-3bef-11ea-9017-5e099ff640c8.png)

**Comment by hmuir28** [comment]
Yup, probably you're right. I'm gonna try it out again today.

**Comment by hmuir28** [comment]
> Maybe you are using the old version, it is working fine
> 
> ![Screenshot 2020-01-21 at 1 41 22 AM](https://user-images.githubusercontent.com/9634816/72747298-2dcf3c00-3bef-11ea-842d-b2c4fa21b54e.png)
> ![Screenshot 2020-01-21 at 1 41 19 AM](https://user-images.githubusercontent.com/9634816/72747306-30ca2c80-3bef-11ea-9017-5e099ff640c8.png)

Sadly, I wasn't able to make it works by installing your node module, however, I made it works directly from your project ... It's strange... I'm trying to figure out what it's occurring, I'll let you know when I find it out

**Comment by godkinmo** [comment]
I find the problem, it happen in my build step to npm
`"babelify": "babel src --out-dir lib --copy-files",`

some file is require full path of my computer
I am going to fix it

**Comment by hmuir28** [comment]
> I find the problem, it happen in my build step to npm
> `"babelify": "babel src --out-dir lib --copy-files",`
> 
> some file is require full path of my computer
> I am going to fix it

Great, let me know when you solve it

**Comment by godkinmo** [comment]
I just update the package, you can run this command to upgrade
`yarn add mdx-vue-deck`

But still having something need to fix, I will fix it when I have time
need to manual to add this two
```
yarn add eslint @vue/cli-plugin-eslint
```

The complete package.json file
```
{
  "name": "test-mdx-vue-deck",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "eject": "mdx-vue-deck eject",
    "start": "mdx-vue-deck dev deck.mdx -c theme.config.js",
    "build": "mdx-vue-deck build deck.mdx -c theme.config.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@vue/cli-plugin-eslint": "^4.1.2",
    "eslint": "^6.8.0",
    "mdx-vue-deck": "^0.1.11"
  }
}
```
